### PR TITLE
39 comparable objects

### LINKED ISSUE #39: Objects should be comparable
`actual.should.equal(expected)` does not compile for objects:

    Error: no property 'equal' for type 'ShouldObject!(Object)'

### PR DESCRIPTION
**Pull request by gedaiu**
fix #39

### CODE REVIEW

File: core/fluentasserts/core/objects.d [hunk 1]
```diff
@@ -35,6 +35,17 @@ struct ShouldObject(T) {
                                            "a `" ~ T.stringof ~ "` instance"),
                                            file, line);
   }
+
+  auto equal(U)(U instance, const string file = __FILE__, const size_t line = __LINE__) {
+    addMessage(" equal ");
+    addValue("`" ~ U.stringof ~ "`");
+    beginCheck;
+
+    bool isEqual = testData.opEquals(instance);
```
Comment (linkrope) [inline core/fluentasserts/core/objects.d]: `object.d` does nice things:
https://github.com/dlang/druntime/blob/master/src/object.d#L138
(`null` handling; symmetric call)

So, you should not call `opEquals` directly:

    bool isEqual = testData == instance;

Comment (gedaiu) [reply core/fluentasserts/core/objects.d]: hmm... i see. I did not know that. Thanks!
